keybinds:
  jump: z
  left: left
  right: right
  nail: x
  dash: c
  super_dash: s
  cast: f
  focus: a
  load_save_state: '['
  livesplit_timer: '-'
commands:
  left: left
  right: right
  turn_left: west
  turn_right: east
  move_extend:
    small: long
    medium: long long
    large: uber
  jump_small: hop
  jump_large: jump
  dash: dash
  super_dash: crystal heart
  nail: nail
  cast: cast
  focus: focus
  panic: panic
  load_save_state: here we go again
